services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - 5173:3000
    env_file: '.env'
    environment:
      - DB_HOST=db
    networks:
      - mediarahan
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    restart: unless-stopped
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - mediarahan-db:/var/lib/postgresql
    networks:
      - mediarahan
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres_user -d postgres_db']
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  mediarahan:
    driver: bridge

volumes:
  mediarahan-db:
    driver: local
