services:
  app:
    image: mediarahan-app:1.0.0
    container_name: mediarahan-app
    build:
      context: .
      args:
        PORT: ${PORT}
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    networks:
        - coolify

  db:
    image: postgres:17
    restart: unless-stopped
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    profiles:
      - local
    volumes:
      - mediarahan-db:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_DATABASE}']
      interval: 5s
      timeout: 5s
      retries: 20

networks:
    coolify:
        external: true
        name: coolify
        attachable: true

volumes:
  mediarahan-db:
    driver: local
