services:
  app:
    build:
      context: .
      args:
        PORT: ${PORT}
        ORIGIN: ${ORIGIN}
    profiles:
      - production
    restart: unless-stopped
    ports:
      - ${PORT:-5173}:${PORT:-5173}
    env_file: '.env'
    environment:
      - DB_HOST=db
    networks:
      - mediarahan
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl -f ${ORIGIN}/health || exit 1']
      interval: 5s
      timeout: 5s
      retries: 20

  db:
    image: postgres:17
    restart: unless-stopped
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - mediarahan-db:/var/lib/postgresql
    networks:
      - mediarahan
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_DATABASE}']
      interval: 5s
      timeout: 5s
      retries: 20

networks:
  mediarahan:
    driver: bridge

volumes:
  mediarahan-db:
    driver: local
